### ISSUE TITLE
Write three notes and get rests above and below notes

### ISSUE THREAD

**Issue by jogama** [JuliaMusic/MusicVisualizations.jl#12]
See linked gist and the comment within: https://gist.github.com/jogama/83d4bb66d7e9266a5f2d02f311058c90

I only expected the half rest at the end. I am not certain if this is a bug or that I'm using the interface incorrectly. If it's the latter, I can update the documentation once corrected. 

Contents of entire gist are pasted here:
```
# https://juliamusic.github.io/JuliaMusic_documentation.jl/latest/blog/drumpatterns/
using MusicManipulations, MusicVisualizations
tpq = 960    # ticks per quarter note
sixt = tpq/4 # duration of sixteenth note
intensity = 50

notes = Notes([ 
Note(name_to_pitch("A5"), intensity, 0, tpq),
Note(name_to_pitch("G4"), intensity, tpq, 2tpq),
Note(name_to_pitch("D4"), intensity, 2tpq, 4tpq)
])
musescore("surprizing_rests.png", notes)
```

The resulting image:
![surprizing_rests](https://user-images.githubusercontent.com/13400532/114801980-d6c10400-9d6a-11eb-924a-cb51309d7bb2.png)

**Comment by Datseris** [comment]
Hi,

The way musescore typesets the notes is unrelated with us, we only provide the convenience function `musescore` that directly plugs the saved MIDI file into musecore. It does nothing else. If you have problems with MuseScore's visualization please open an issue there providing your midi file as well I guess.
